#!/bin/sh
### BEGIN INIT INFO
# Provides: sncstart
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start and Stop
# Description:
### END INIT INFO


start_snc() {
    SNCExec -c -d
}

case "$1" in
    start)
        echo "Starting SNCExec"
        start_snc
        ;;

    stop)
        echo "Stopping SNCExec"
        killall SNCExec
        ;;

    restart)
        echo "Stopping SNCExec"
        killall SNCExec
        sleep 3
        echo "Starting SNCExec"
        start_snc
        ;;

    *)
        echo "Usage: /etc/init.d/sncstart {start|stop|restart}"
        exit 2
esac

